spring.application.name=project-1

## DB Connection
# change local host number and name of the database in case you decide to use a different name
spring.datasource.url=jdbc:postgresql://localhost:5432/project-1
# change this to you username
spring.datasource.username=postgres
# change this to your password
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect